import {verifyEvidence} from '../../../lib/evidence';
import {AnalysisResult,EvidenceItem,ProductDNA,ProductInput} from '../../../lib/types';
import {GeminiClient,GeminiProviderError,getGeminiConfig} from './client';
import {buildAnalystPrompt,buildChatPrompt,chatSchema,reportSchema} from './prompts';
import type {EvidenceClaim,AnalystInput,GeminiChatResponse,GeminiReport,ResearchGap} from './types';
import {estimateCost,estimateTokens,recordGeminiUsage} from './usage';

const statuses=new Set(['VERIFIED','INFERRED','UNKNOWN','CONFLICTING','INSUFFICIENT EVIDENCE']);
const record=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'?value as Record<string,unknown>:{};
const text=(value:unknown,fallback='')=>typeof value==='string'?value:fallback;
function safeIds(value:unknown,valid:Set<string>){return Array.isArray(value)?value.filter(id=>typeof id==='string'&&valid.has(id)):[];}
export function normalizeClaim(value:unknown,valid:Set<string>):EvidenceClaim{
 const source=record(value);const evidenceIds=safeIds(source.evidenceIds,valid);let status=text(source.status,'UNKNOWN').toUpperCase();if(!statuses.has(status))status='UNKNOWN';if((status==='VERIFIED'||status==='INFERRED'||status==='CONFLICTING')&&!evidenceIds.length)status='INSUFFICIENT EVIDENCE';return{claim:text(source.claim,'Insufficient evidence.'),status:evidenceIds.length?status as EvidenceClaim['status']:(status==='VERIFIED'||status==='INFERRED'||status==='CONFLICTING'?'INSUFFICIENT EVIDENCE':status as EvidenceClaim['status']),evidenceIds};
}
function normalizeSection(value:unknown,valid:Set<string>){const source=record(value);return{summary:normalizeClaim(source.summary,valid),claims:Array.isArray(source.claims)?source.claims.map(item=>normalizeClaim(item,valid)):[]};}

export function detectResearchGaps(product:ProductInput,result:AnalysisResult,evidence=result.evidence):ResearchGap[]{
 const gaps:ResearchGap[]=[];const external=(terms:string[])=>evidence.filter(item=>terms.some(term=>item.claim.toLowerCase().includes(term))&&item.sourceType!=='manual'&&item.sourceType!=='demo');
 const demand=external(['demand']);if(!demand.length)gaps.push({missingField:'local demand',reason:'No connected local demand source is available.',suggestedSourceType:'search or marketplace',priority:'high',evidenceIds:[]});
 if(product.productCost<=0||!evidence.some(item=>item.claim.toLowerCase().includes('profit')&&item.verificationStatus==='verified'))gaps.push({missingField:'supplier cost',reason:'Supplier cost is missing or not verified by a source.',suggestedSourceType:'pricing or marketplace',priority:'high',evidenceIds:[]});
 if(!external(['competitor','pricing']).length)gaps.push({missingField:'competitor pricing',reason:'No connected competitor pricing source is available.',suggestedSourceType:'marketplace or pricing',priority:'high',evidenceIds:[]});
 if(product.reviewCount<30||!external(['review']).length)gaps.push({missingField:'insufficient reviews',reason:'Review volume or an external review source is insufficient.',suggestedSourceType:'reviews or marketplace',priority:'medium',evidenceIds:evidence.filter(item=>item.claim.toLowerCase().includes('buyer')).map(item=>item.id)});
 const stale=evidence.filter(item=>item.freshness==='stale'||item.freshness==='expired'||item.verificationStatus==='stale').map(item=>item.id);if(stale.length)gaps.push({missingField:'stale sources',reason:'Some evidence is outside its configured freshness window.',suggestedSourceType:'the original source',priority:'medium',evidenceIds:stale});
 const verification=verifyEvidence(evidence);if(verification.conflicts.length)gaps.push({missingField:'conflicting values',reason:'Sources disagree on one or more claims.',suggestedSourceType:'cross-source verification',priority:'high',evidenceIds:verification.conflicts});
 return gaps;
}

export function buildAnalystInput(product:ProductInput,result:AnalysisResult,region='User-defined'):AnalystInput{
 const verification=verifyEvidence(result.evidence);const researchGaps=detectResearchGaps(product,result,result.evidence);return{product,evidence:result.evidence,verification,productDNA:result.productDNA,trend:result.trend,buyerIntent:result.buyerIntent,competition:result.productDNA.competition,pricing:result.productDNA.price,profit:result.profit,risk:result.risk,researchGaps,region};
}

function parseText(raw:string){const cleaned=raw.trim().replace(/^```(?:json)?/i,'').replace(/```$/,'').trim();try{return JSON.parse(cleaned) as unknown;}catch{throw new GeminiProviderError('malformed_json','Gemini response was not valid JSON.');}}
function requireField(source:Record<string,unknown>,key:string){if(!(key in source))throw new GeminiProviderError('invalid_response',`Gemini response omitted ${key}.`);}
export function normalizeReport(raw:unknown,input:AnalystInput,model:string):GeminiReport{
 const source=record(raw);const required=['executiveSummary','demandInterpretation','trendInterpretation','buyerIntentInterpretation','competitionInterpretation','pricingInterpretation','profitInterpretation','riskInterpretation','evidenceGaps','researchRecommendations','testPlan','shouldISell'];required.forEach(key=>requireField(source,key));const valid=new Set(input.evidence.map(item=>item.id));const should=record(source.shouldISell);
 const normalizeClaims=(value:unknown)=>Array.isArray(value)?value.map(item=>normalizeClaim(item,valid)):[];
 const testPlan=Array.isArray(source.testPlan)?source.testPlan.map(item=>{const row=record(item);return{step:text(row.step,'Unknown step.'),successMetric:text(row.successMetric,'Unknown success metric.'),guardrail:text(row.guardrail,'Unknown guardrail.'),evidenceIds:safeIds(row.evidenceIds,valid)};}):[];
 const gaps=Array.isArray(source.evidenceGaps)?source.evidenceGaps.map(item=>{const row=record(item);return{missingField:text(row.missingField,'Unknown gap'),reason:text(row.reason,'Insufficient evidence.'),suggestedSourceType:text(row.suggestedSourceType,'unknown'),priority:(['high','medium','low'].includes(text(row.priority))?text(row.priority):'medium') as ResearchGap['priority'],evidenceIds:safeIds(row.evidenceIds,valid)};}):[];
 return{executiveSummary:normalizeClaim(source.executiveSummary,valid),demandInterpretation:normalizeSection(source.demandInterpretation,valid),trendInterpretation:normalizeSection(source.trendInterpretation,valid),buyerIntentInterpretation:normalizeSection(source.buyerIntentInterpretation,valid),competitionInterpretation:normalizeSection(source.competitionInterpretation,valid),pricingInterpretation:normalizeSection(source.pricingInterpretation,valid),profitInterpretation:normalizeSection(source.profitInterpretation,valid),riskInterpretation:normalizeSection(source.riskInterpretation,valid),evidenceGaps:gaps,researchRecommendations:normalizeClaims(source.researchRecommendations),testPlan,shouldISell:{supportingEvidence:normalizeClaims(should.supportingEvidence),concerns:normalizeClaims(should.concerns),missingEvidence:normalizeClaims(should.missingEvidence),assumptions:normalizeClaims(should.assumptions),controlledTestRecommendation:normalizeClaim(should.controlledTestRecommendation,valid)},metadata:{model,generatedAt:new Date().toISOString(),evidenceAnalyzed:input.evidence.length,evidenceExcluded:input.evidence.filter(item=>item.verificationStatus==='conflict'||item.verificationStatus==='stale'||item.verificationStatus==='missing').length,lastAnalysisTime:new Date().toISOString()}};
}

export function buildFallbackReport(input:AnalystInput,model='not-connected'):GeminiReport{
 const valid=new Set(input.evidence.map(item=>item.id));const known=input.evidence.filter(item=>item.verificationStatus==='verified').map(item=>item.id);const unknown:EvidenceClaim={claim:'Gemini Not Connected. No AI interpretation was generated.',status:'UNKNOWN',evidenceIds:[]};const section={summary:unknown,claims:[]};return{executiveSummary:unknown,demandInterpretation:section,trendInterpretation:section,buyerIntentInterpretation:section,competitionInterpretation:section,pricingInterpretation:section,profitInterpretation:section,riskInterpretation:section,evidenceGaps:input.researchGaps,researchRecommendations:[],testPlan:[],shouldISell:{supportingEvidence:known.length?[{claim:'Verified workspace inputs are available for review.',status:'VERIFIED',evidenceIds:known}]:[],concerns:[],missingEvidence:input.researchGaps.map(gap=>({claim:gap.reason,status:'INSUFFICIENT EVIDENCE' as const,evidenceIds:gap.evidenceIds.filter(id=>valid.has(id))})),assumptions:[],controlledTestRecommendation:unknown},metadata:{model,generatedAt:new Date().toISOString(),evidenceAnalyzed:input.evidence.length,evidenceExcluded:input.evidence.filter(item=>item.verificationStatus!=='verified').length,lastAnalysisTime:new Date().toISOString()}};
}

export async function generateGeminiReport(input:AnalystInput,client=new GeminiClient()){const prompt=buildAnalystPrompt(input);const requestId=`gemini-report-${Date.now()}`;try{const response=await client.generateContent(prompt,reportSchema);const rawText=response.data.candidates?.[0]?.content?.parts?.map(part=>part.text||'').join('').trim()||'';const report=normalizeReport(parseText(rawText),input,client.config.model);recordGeminiUsage({requestId,timestamp:new Date().toISOString(),model:client.config.model,estimatedInputTokens:response.inputTokens??estimateTokens(prompt),estimatedOutputTokens:response.outputTokens??estimateTokens(rawText),success:true,estimatedCost:estimateCost(response.inputTokens??estimateTokens(prompt),response.outputTokens??estimateTokens(rawText)),operation:'report',evidenceAnalyzed:input.evidence.length,evidenceExcluded:input.verification.conflicts.length+input.verification.stale.length+input.verification.missingClaims.length});return report;}catch(error){const providerError=error instanceof GeminiProviderError?error:new GeminiProviderError('unavailable','Gemini report failed.');recordGeminiUsage({requestId,timestamp:new Date().toISOString(),model:client.config.model,estimatedInputTokens:estimateTokens(prompt),estimatedOutputTokens:null,success:false,estimatedCost:null,operation:'report',errorCode:providerError.code});throw providerError;}}
export async function answerWithGemini(input:AnalystInput,question:string,client=new GeminiClient()):Promise<GeminiChatResponse>{const prompt=buildChatPrompt(input,question);const requestId=`gemini-chat-${Date.now()}`;try{const response=await client.generateContent(prompt,chatSchema);const rawText=response.data.candidates?.[0]?.content?.parts?.map(part=>part.text||'').join('').trim()||'';const source=parseText(rawText) as Record<string,unknown>;const valid=new Set(input.evidence.map(item=>item.id));const result={answer:normalizeClaim(source.answer,valid),supportingEvidence:Array.isArray(source.supportingEvidence)?source.supportingEvidence.map(item=>normalizeClaim(item,valid)):[],researchGaps:Array.isArray(source.researchGaps)?source.researchGaps.map(item=>{const row=record(item);return{missingField:text(row.missingField,'Unknown gap'),reason:text(row.reason,'Insufficient evidence.'),suggestedSourceType:text(row.suggestedSourceType,'unknown'),priority:(['high','medium','low'].includes(text(row.priority))?text(row.priority):'medium') as ResearchGap['priority'],evidenceIds:safeIds(row.evidenceIds,valid)};}):[]};recordGeminiUsage({requestId,timestamp:new Date().toISOString(),model:client.config.model,estimatedInputTokens:response.inputTokens??estimateTokens(prompt),estimatedOutputTokens:response.outputTokens??estimateTokens(rawText),success:true,estimatedCost:estimateCost(response.inputTokens??estimateTokens(prompt),response.outputTokens??estimateTokens(rawText)),operation:'chat'});return result;}catch(error){const providerError=error instanceof GeminiProviderError?error:new GeminiProviderError('unavailable','Gemini chat failed.');recordGeminiUsage({requestId,timestamp:new Date().toISOString(),model:client.config.model,estimatedInputTokens:estimateTokens(prompt),estimatedOutputTokens:null,success:false,estimatedCost:null,operation:'chat',errorCode:providerError.code});throw providerError;}}
