import type {GoogleAdsConfig,GoogleAdsHealth,GoogleAdsKeywordRequest,GoogleAdsRawResponse,GoogleAdsProviderError} from './types';
import {GoogleAdsProviderError as ProviderError} from './types';

const API_BASE='https://googleads.googleapis.com/v25';
const OAUTH_URL='https://oauth2.googleapis.com/token';
const RETRYABLE=new Set([408,425,429,500,502,503,504]);
const positive=(value:string|undefined,fallback:number)=>{const n=Number(value);return Number.isFinite(n)&&n>0?Math.floor(n):fallback;};
export function normalizeCustomerId(value:string|undefined){const id=(value||'').replace(/[^0-9]/g,'');return /^\d{6,20}$/.test(id)?id:'';}
export function getGoogleAdsConfig(env:Record<string,string|undefined>=process.env):GoogleAdsConfig{const rawCustomer=env.GOOGLE_ADS_CUSTOMER_ID;return{clientId:env.GOOGLE_ADS_CLIENT_ID?.trim()||undefined,clientSecret:env.GOOGLE_ADS_CLIENT_SECRET?.trim()||undefined,refreshToken:env.GOOGLE_ADS_REFRESH_TOKEN?.trim()||undefined,customerId:rawCustomer===undefined?'1629155768':normalizeCustomerId(rawCustomer),cloudProjectId:env.GOOGLE_CLOUD_PROJECT_ID?.trim()||undefined,developerToken:env.GOOGLE_ADS_DEVELOPER_TOKEN?.trim()||undefined,loginCustomerId:normalizeCustomerId(env.GOOGLE_ADS_LOGIN_CUSTOMER_ID)||undefined,baseUrl:(env.GOOGLE_ADS_API_BASE_URL||API_BASE).replace(/\/$/,''),oauthUrl:(env.GOOGLE_ADS_OAUTH_URL||OAUTH_URL).replace(/\/$/,''),timeoutMs:positive(env.GOOGLE_ADS_TIMEOUT_MS,15000),maxRetries:Math.min(4,positive(env.GOOGLE_ADS_MAX_RETRIES,2))};}
export function validateGoogleAdsConfig(config:GoogleAdsConfig){if(!config.clientId||!config.clientSecret||!config.refreshToken)return'Google Ads OAuth credentials are not configured.';if(!config.customerId)return'GOOGLE_ADS_CUSTOMER_ID is invalid.';return null;}
const delay=(attempt:number)=>new Promise<void>(resolve=>setTimeout(resolve,Math.min(4000,250*2**attempt)));
function statusError(status:number){if(status===401)return new ProviderError('invalid_auth','Google Ads authentication was rejected.',status);if(status===403)return new ProviderError('permission_denied','Google Ads access or developer-token permission was denied.',status);if(status===429)return new ProviderError('rate_limited','Google Ads rate limit reached.',status);if(status===402)return new ProviderError('quota_exhausted','Google Ads quota was exhausted.',status);return new ProviderError('unavailable',`Google Ads request failed with status ${status}.`,status);}
export class GoogleAdsClient{
 constructor(public readonly config:GoogleAdsConfig=getGoogleAdsConfig()){}
 private requireConfig(){const message=validateGoogleAdsConfig(this.config);if(message)throw new ProviderError(message.includes('invalid')?'invalid_configuration':'missing_credentials',message);}
 private async accessToken(attempt=0):Promise<string>{this.requireConfig();const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.config.timeoutMs);try{const body=new URLSearchParams({client_id:this.config.clientId!,client_secret:this.config.clientSecret!,refresh_token:this.config.refreshToken!,grant_type:'refresh_token'});let response:Response;try{response=await fetch(this.config.oauthUrl,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body,signal:controller.signal});}catch(error){if(attempt<this.config.maxRetries){await delay(attempt);return this.accessToken(attempt+1);}if((error as Error)?.name==='AbortError')throw new ProviderError('timeout','Google Ads OAuth request timed out.');throw new ProviderError('unavailable','Google Ads OAuth request could not be reached.');}if(!response.ok){if(RETRYABLE.has(response.status)&&attempt<this.config.maxRetries){await delay(attempt);return this.accessToken(attempt+1);}throw statusError(response.status);}const data=await response.json() as {access_token?:string;error?:string};if(!data.access_token)throw new ProviderError('invalid_auth','Google Ads OAuth response did not include an access token.');return data.access_token;}catch(error){if(error instanceof ProviderError)throw error;throw new ProviderError('malformed_response','Google Ads OAuth response was malformed.');}finally{clearTimeout(timer);}}
 async request<T>(path:string,body:Record<string,unknown>,attempt=0,method:'GET'|'POST'='POST'):Promise<T>{const token=await this.accessToken();const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.config.timeoutMs);try{const headers=new Headers({'Authorization':`Bearer ${token}`,'Accept':'application/json'});if(method==='POST')headers.set('Content-Type','application/json');if(this.config.developerToken)headers.set('developer-token',this.config.developerToken);if(this.config.loginCustomerId)headers.set('login-customer-id',this.config.loginCustomerId);let response:Response;try{response=await fetch(`${this.config.baseUrl}${path}`,{method,headers,body:method==='POST'?JSON.stringify(body):undefined,signal:controller.signal});}catch(error){if(attempt<this.config.maxRetries){await delay(attempt);return this.request<T>(path,body,attempt+1,method);}if((error as Error)?.name==='AbortError')throw new ProviderError('timeout','Google Ads request timed out.');throw new ProviderError('unavailable','Google Ads request could not be reached.');}if(!response.ok){if(RETRYABLE.has(response.status)&&attempt<this.config.maxRetries){await delay(attempt);return this.request<T>(path,body,attempt+1,method);}throw statusError(response.status);}try{return await response.json() as T;}catch{throw new ProviderError('malformed_response','Google Ads returned malformed JSON.',response.status);}}finally{clearTimeout(timer);}}
 async generateKeywordIdeas(request:GoogleAdsKeywordRequest){const customerId=normalizeCustomerId(request.customerId)||this.config.customerId;if(!customerId)throw new ProviderError('invalid_configuration','A valid Google Ads customer ID is required.');const seedKeywords=(request.seedKeywords||[]).map(item=>item.trim()).filter(Boolean);const query=request.query?.trim();if(query&&!seedKeywords.includes(query))seedKeywords.unshift(query);if(!seedKeywords.length&&!request.seedUrl)throw new ProviderError('unsupported','A seed keyword or URL is required.');const body:Record<string,unknown>={keywordPlanNetwork:request.network==='GOOGLE_SEARCH'?'GOOGLE_SEARCH':'GOOGLE_SEARCH_AND_PARTNERS'};if(request.languageConstant)body.language= request.languageConstant;if(request.geoTargetConstants?.length)body.geoTargetConstants=request.geoTargetConstants;if(request.includeAdultKeywords!==undefined)body.includeAdultKeywords=request.includeAdultKeywords;if(seedKeywords.length)body.keywordSeed={keywords:seedKeywords};if(request.seedUrl)body.urlSeed={url:request.seedUrl};return this.request<GoogleAdsRawResponse>(`/customers/${customerId}:generateKeywordIdeas`,body);}
 async listAccessibleCustomers(){return this.request<{resourceNames?:string[]}>('/customers:listAccessibleCustomers',{},0,'GET');}
 async verifyAuthentication():Promise<GoogleAdsHealth>{const checkedAt=new Date().toISOString();const message=validateGoogleAdsConfig(this.config);if(message)return{provider:'google-ads',status:'unconfigured',checkedAt,customerId:this.config.customerId,message,requestCount:0,lastSuccessfulResearch:null,lastError:null};const started=Date.now();try{await this.listAccessibleCustomers();return{provider:'google-ads',status:this.config.developerToken?'healthy':'degraded',checkedAt,latencyMs:Date.now()-started,customerId:this.config.customerId,message:this.config.developerToken?'Google Ads authentication verified.':'OAuth verified; GOOGLE_ADS_DEVELOPER_TOKEN is not configured.',requestCount:0,lastSuccessfulResearch:null,lastError:null};}catch(error){const providerError=error instanceof ProviderError?error:new ProviderError('unavailable','Google Ads health check failed.');return{provider:'google-ads',status:providerError.code==='rate_limited'?'rate-limited':providerError.code==='invalid_auth'||providerError.code==='permission_denied'?'unhealthy':'degraded',checkedAt,latencyMs:Date.now()-started,customerId:this.config.customerId,message:providerError.message,requestCount:0,lastSuccessfulResearch:null,lastError:providerError.code};}}
}
