import {createEvidence,verifyEvidence} from '../../evidence';
import type {EvidenceItem} from '../../types';
import type {GoogleAdsKeywordRequest,GoogleAdsRawIdea,GoogleAdsRawMetric,GoogleAdsRawResponse,GoogleAdsKeywordResult,SeoKeyword,SeoOpportunity} from './types';

const text=(value:unknown)=>typeof value==='string'?value.trim():'';
const numberOrNull=(value:unknown)=>{const valueNumber=typeof value==='number'?value:Number(value);return Number.isFinite(valueNumber)?valueNumber:null;};
export function classifySearchIntent(keyword:string):SeoKeyword['intent']{const value=keyword.toLowerCase();if(/\b(how|what|why|guide|教程|tutorial|meaning|best way)\b/.test(value))return'informational';if(/\b(buy|buying|order|price|cheap|deal|quote|hire|book|near me|discount)\b/.test(value))return'transactional';if(/\b(best|top|service|agency|developer|software|solution|compare|review)\b/.test(value))return'commercial';if(/\b(login|official|website|facebook|instagram|youtube)\b/.test(value))return'navigational';return'unknown';}
const metricValue=(metric:GoogleAdsRawMetric|undefined,key:string)=>metric?metric[key]:undefined;
function metricEvidence(keyword:string,metric:GoogleAdsRawMetric|undefined,key:string,claim:string,request:GoogleAdsKeywordRequest,collectedAt:string):EvidenceItem|null{const value=metricValue(metric,key);if(value===undefined||value===null||value==='')return null;const sourceId=`${keyword}-${key}`;return createEvidence({id:`google-ads-${sourceId.replace(/[^a-z0-9]+/gi,'-').slice(0,70)}`,claim,source:'Google Ads Keyword Planner',sourceType:'ads',sourceUrl:'https://ads.google.com/aw/keywordplanner',sourceId,region:request.location||'Unspecified',originalValue:JSON.stringify(value),normalizedValue:typeof value==='string'?value:JSON.stringify(value),collectedAt,status:'unverified',confidence:.85,metadata:{provider:'google-ads',query:keyword,category:'seo-keyword',tags:['GOOGLE ADS','KEYWORD METRIC'],notes:'Returned by Google Ads; absence means unavailable.'}});}
function keywordEvidence(keyword:string,idea:GoogleAdsRawIdea,request:GoogleAdsKeywordRequest,collectedAt:string):EvidenceItem{return createEvidence({id:`google-ads-keyword-${keyword.replace(/[^a-z0-9]+/gi,'-').slice(0,80)}`,claim:`Google Ads keyword idea: ${keyword}`,source:'Google Ads Keyword Planner',sourceType:'ads',sourceUrl:'https://ads.google.com/aw/keywordplanner',sourceId:`keyword-${keyword}`,region:request.location||'Unspecified',originalValue:JSON.stringify(idea),normalizedValue:keyword,collectedAt,status:'unverified',confidence:.8,metadata:{provider:'google-ads',query:keyword,category:'seo-keyword',tags:['GOOGLE ADS','KEYWORD IDEA']}});}
export function normalizeGoogleAdsResponse(response:GoogleAdsRawResponse,request:GoogleAdsKeywordRequest,requestId='google-ads-normalize'):GoogleAdsKeywordResult{
 const collectedAt=new Date().toISOString();const ideas=response.results||[];const allEvidence:EvidenceItem[]=[];const rawKeywords:SeoKeyword[]=[];
 ideas.forEach((idea,index)=>{const keyword=text(idea.text);if(!keyword)return;const metric=idea.keywordIdeaMetrics;const base=keywordEvidence(keyword,idea,request,collectedAt);allEvidence.push(base);const metrics=[metricEvidence(keyword,metric,'avgMonthlySearches',`Google Ads average monthly searches for ${keyword}`,request,collectedAt),metricEvidence(keyword,metric,'competition',`Google Ads competition for ${keyword}`,request,collectedAt),metricEvidence(keyword,metric,'competitionIndex',`Google Ads competition index for ${keyword}`,request,collectedAt),metricEvidence(keyword,metric,'lowTopOfPageBidMicros',`Google Ads low top of page bid for ${keyword}`,request,collectedAt),metricEvidence(keyword,metric,'highTopOfPageBidMicros',`Google Ads high top of page bid for ${keyword}`,request,collectedAt),metricEvidence(keyword,metric,'monthlySearchVolumes',`Google Ads historical monthly searches for ${keyword}`,request,collectedAt)].filter((item):item is EvidenceItem=>Boolean(item));allEvidence.push(...metrics);const low=numberOrNull(metric?.lowTopOfPageBidMicros);const high=numberOrNull(metric?.highTopOfPageBidMicros);rawKeywords.push({keyword,intent:classifySearchIntent(keyword),location:request.location||'Unspecified',language:request.language||'unspecified',searchVolume:numberOrNull(metric?.avgMonthlySearches),competition:text(metric?.competition)||null,competitionIndex:numberOrNull(metric?.competitionIndex),cpc:low!==null||high!==null?{low:low===null?null:low/1000000,high:high===null?null:high/1000000,currency:'account currency; micros converted'}:null,historicalMetrics:Array.isArray(metric?.monthlySearchVolumes)?metric!.monthlySearchVolumes!:null,source:'Google Ads Keyword Planner',sourceTimestamp:collectedAt,evidenceId:base.id,freshness:base.freshness,verificationStatus:base.verificationStatus,confidence:base.confidence});});
 const verification=verifyEvidence(allEvidence);const byId=new Map(verification.verified.map(item=>[item.id,item]));const keywords=rawKeywords.map(item=>{const evidence=byId.get(item.evidenceId)||allEvidence.find(value=>value.id===item.evidenceId)!;return{...item,freshness:evidence.freshness,verificationStatus:evidence.verificationStatus,confidence:evidence.confidence};});const opportunities=buildSeoOpportunities(keywords,allEvidence,request.query||request.seedKeywords?.[0]||'');return{keywords,opportunities,evidence:verification.verified,verification,query:request.query||request.seedKeywords?.join(', ')||request.seedUrl||'',location:request.location||'Unspecified',language:request.language||'unspecified',sourceStatus:keywords.length?'success':'empty',requestId,latencyMs:0};
}
export function buildSeoOpportunities(keywords:SeoKeyword[],evidence:EvidenceItem[],relevanceText=''):SeoOpportunity[]{const relevanceTokens=relevanceText.toLowerCase().split(/\W+/).filter(Boolean);return keywords.map(item=>{const states:string[]=[];const evidenceIds=evidence.filter(record=>record.claim.toLowerCase().includes(item.keyword.toLowerCase())).map(record=>record.id);const intent=item.intent;if(intent==='commercial')states.push('High Commercial Intent');if(intent==='transactional')states.push('High Buyer Intent');if(item.competition&&/HIGH|MEDIUM|LOW/i.test(item.competition)&&item.competition.toUpperCase().includes('HIGH'))states.push('Competitive');const history=item.historicalMetrics||[];if(history.length>=2){const first=numberOrNull(history[0]?.monthlySearches??history[0]?.avgMonthlySearches);const last=numberOrNull(history[history.length-1]?.monthlySearches??history[history.length-1]?.avgMonthlySearches);if(first!==null&&last!==null&&last>first)states.push('Rising');}if(!item.searchVolume&&!item.competition&&!item.cpc)states.push('Low Evidence','Insufficient Evidence');else if(item.verificationStatus==='conflict')states.push('CONFLICT DETECTED');else if(item.verificationStatus!=='verified')states.push('Evidence Needs Verification');if((intent==='commercial'||intent==='transactional')&&item.searchVolume!==null&&item.competition!==null&&item.verificationStatus!=='conflict')states.push('Strong Opportunity Signal');if(!states.length)states.push('Evidence Ready');const matched=relevanceTokens.filter(token=>item.keyword.toLowerCase().includes(token)).length;return{keyword:item.keyword,states,intent,relevance:relevanceTokens.length?(matched>=Math.min(2,relevanceTokens.length)?'high':matched?'medium':'low'):'unknown',evidenceIds,reason:'States reflect only returned Google Ads metrics, keyword language, and evidence status; they are not a demand forecast.'};});}
