"use client";
import {useEffect,useState} from 'react';

type Capability={capability:string;status:string;message:string;count?:number};
type Health={status:string;message:string;capabilities:Record<string,Capability>;userName?:string};

const label=(status?:string)=>status==='connected'?'CONNECTED':status==='permission_error'?'PERMISSION ERROR':status==='auth_error'?'AUTH ERROR':status==='rate_limited'?'RATE LIMITED':status==='unavailable'?'UNAVAILABLE':'NOT CONNECTED';
const badgeClass=(status?:string)=>status==='connected'?'healthy':status==='rate_limited'?'degraded':status==='permission_error'||status==='auth_error'?'unhealthy':'degraded';

export default function MetaIntelligencePanel(){
  const[health,setHealth]=useState<Health|null>(null); const[loading,setLoading]=useState(false); const[action,setAction]=useState(''); const[message,setMessage]=useState('');
  async function verify(){setLoading(true);setMessage('');try{const response=await fetch('/api/meta/status');const json=await response.json();setHealth(json.health||null);setMessage(json.health?.message||'Meta status updated.');}catch{setMessage('Meta status is unavailable.');}finally{setLoading(false);}}
  useEffect(()=>{void verify();},[]);
  async function run(path:string,body?:Record<string,unknown>){setLoading(true);setAction(path);setMessage('');try{const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const json=await response.json();if(!response.ok){setMessage(json.error||'Meta capability is unavailable.');return;}const result=json.result;const count=result?.counts?.evidence??json.pages?.length??json.accounts?.length??json.catalogs?.length??(json.account?1:0);setMessage(`${json.status||'CONNECTED'} · ${typeof count==='number'?`${count} records`: 'request completed'}`);await verify();}catch{setMessage('Meta request failed.');}finally{setLoading(false);setAction('');}}
  const capabilities=[['facebook','Facebook Pages'],['instagram','Instagram'],['ads','Ads'],['catalog','Catalog'],['adLibrary','Ad Library']];
  const overallStatus=health?.status==='healthy'?'connected':health?.status==='unhealthy'?'auth_error':health?.status==='rate-limited'?'rate_limited':health?.status;
  return <section className="meta-panel"><div className="section-head compact"><div><span className="eyebrow">META INTELLIGENCE</span><h3>Facebook, Instagram, Ads & Catalog</h3></div><span className={`health-badge ${badgeClass(overallStatus)}`}>Meta {health?.status==='healthy'?'CONNECTED':health?.status==='unhealthy'?'AUTH ERROR':health?.status==='rate-limited'?'RATE LIMITED':health?.status==='degraded'?'PARTIAL':'NOT CONNECTED'}</span></div><p className="micro">Read-only Meta evidence is normalized and verified before intelligence use. Spend, sales and conversions remain unavailable unless Meta returns them.</p><div className="meta-capabilities">{capabilities.map(([key,name])=>{const item=health?.capabilities?.[key];return <div className="meta-capability" key={key}><span>{name}</span><strong className={`health-badge ${badgeClass(item?.status)}`}>{label(item?.status)}</strong>{item?.count!==undefined&&<small>{item.count} available</small>}</div>;})}</div><div className="meta-actions"><button className="text-button" type="button" disabled={loading} onClick={verify}>{loading&&!action?'Verifying…':'Connect / Verify'}</button><button className="text-button" type="button" disabled={loading} onClick={()=>run('/api/meta/pages')}>View Pages</button><button className="text-button" type="button" disabled={loading} onClick={()=>run('/api/meta/ad-accounts')}>View Ad Accounts</button><button className="text-button" type="button" disabled={loading} onClick={()=>run('/api/meta/catalogs')}>View Catalogs</button><button className="text-button" type="button" disabled={loading} onClick={()=>run('/api/meta/ads/research',{region:'Pakistan'})}>Research Ads</button><button className="text-button" type="button" disabled={loading} onClick={()=>run('/api/meta/research',{capability:'ads',region:'Pakistan'})}>Analyze Meta Signals</button></div>{message&&<p className="micro meta-message">{message}</p>}</section>;
}
