import {verifyEvidence} from '../evidence';
import type {EvidenceItem,VerificationReport} from '../types';
import type {SerpApiResearchResult} from '../sources/serpapi/types';
import type {GoogleAdsKeywordResult,SeoKeyword,SeoOpportunity} from '../sources/google-ads/types';

export interface SeoResearchInput{query:string;productService:string;region:string;language:string;intent?:SeoKeyword['intent'];}
export interface SeoReport{primaryKeywordOpportunities:SeoOpportunity[];longTailOpportunities:string[];commercialKeywords:string[];transactionalKeywords:string[];supportingKeywords:string[];faqOpportunities:string[];contentTopics:string[];evidenceQuality:'strong'|'mixed'|'low'|'none';researchGaps:string[];recommendedNextActions:string[];}
export interface SeoResearchResult{query:string;productService:string;region:string;language:string;researchTimestamp:string;keywords:SeoKeyword[];opportunities:SeoOpportunity[];evidence:EvidenceItem[];verification:VerificationReport;googleAds:GoogleAdsKeywordResult|null;serpApi:SerpApiResearchResult|null;report:SeoReport;}

const unique=(items:string[])=>[...new Set(items.filter(Boolean))];
function reportFor(keywords:SeoKeyword[],opportunities:SeoOpportunity[],evidence:EvidenceItem[],verification:VerificationReport):SeoReport{const commercial=keywords.filter(item=>item.intent==='commercial').map(item=>item.keyword);const transactional=keywords.filter(item=>item.intent==='transactional').map(item=>item.keyword);const longTail=keywords.filter(item=>item.keyword.trim().split(/\s+/).length>=3).map(item=>item.keyword);const supporting=keywords.filter(item=>item.intent==='informational'||item.intent==='unknown').map(item=>item.keyword);const faq=keywords.filter(item=>item.intent==='informational').map(item=>item.keyword);const topics=unique([...commercial,...transactional,...supporting].map(item=>item));const gaps:string[]=[];if(!keywords.length)gaps.push('No Google Ads keyword ideas were returned.');if(keywords.some(item=>item.searchVolume===null))gaps.push('Search volume is missing for one or more keywords.');if(keywords.some(item=>item.competition===null))gaps.push('Competition is missing for one or more keywords.');if(keywords.some(item=>item.cpc===null))gaps.push('CPC is missing for one or more keywords.');if(verification.conflicts.length)gaps.push('CONFLICT DETECTED: source values require review.');if(verification.stale.length)gaps.push('Some evidence is stale or expired.');if(!evidence.length)gaps.push('No verified external evidence is available.');const verified=evidence.filter(item=>item.verificationStatus==='verified').length;const quality=!evidence.length?'none':verification.conflicts.length?'mixed':verified? 'strong':'low';return{primaryKeywordOpportunities:opportunities.filter(item=>item.states.includes('Strong Opportunity Signal')||item.states.includes('Evidence Ready')),longTailOpportunities:unique(longTail),commercialKeywords:unique(commercial),transactionalKeywords:unique(transactional),supportingKeywords:unique(supporting),faqOpportunities:unique(faq),contentTopics:unique(topics),evidenceQuality:quality,researchGaps:unique(gaps),recommendedNextActions:unique([!keywords.length?'Connect Google Ads credentials and verify Keyword Planner access.':'Review keyword evidence and select a controlled content or campaign test.',verification.conflicts.length?'Resolve conflicting source values before relying on them.':'Keep source timestamps and freshness visible.',keywords.some(item=>item.searchVolume===null)?'Request access to the returned metrics or use another connected source.':'Do not treat keyword presence as demand proof.'])};}
export function combineSeoIntelligence(input:SeoResearchInput,googleAds:GoogleAdsKeywordResult|null,serpApi:SerpApiResearchResult|null):SeoResearchResult{const googleEvidence=googleAds?.evidence||[];const serpEvidence=serpApi?.evidence||[];const allEvidence=[...googleEvidence,...serpEvidence];const verification=verifyEvidence(allEvidence);const verifiedById=new Map(verification.verified.map(item=>[item.id,item]));const keywords=(googleAds?.keywords||[]).map(keyword=>{const evidence=verifiedById.get(keyword.evidenceId);return evidence?{...keyword,freshness:evidence.freshness,verificationStatus:evidence.verificationStatus,confidence:evidence.confidence}:keyword;});const serpSignal=serpApi?.evidence.length? 'SERP presence observed; it is not sales or demand proof.':null;const opportunities=(googleAds?.opportunities||[]).map(item=>serpSignal?{...item,states:item.states.includes('SERP Presence Observed')?item.states:[...item.states,'SERP Presence Observed'],reason:`${item.reason} ${serpSignal}`}:item);return{query:input.query,productService:input.productService,region:input.region,language:input.language,researchTimestamp:new Date().toISOString(),keywords,opportunities,evidence:verification.verified,verification,googleAds,serpApi,report:reportFor(keywords,opportunities,verification.verified,verification)};}
