import {NextResponse} from 'next/server';
import {createGoogleAdsAdapter,GoogleAdsProviderError} from '../../../../lib/sources/google-ads';
import {createSerpApiAdapter,SerpApiError} from '../../../../lib/sources/serpapi';
import {combineSeoIntelligence} from '../../../../lib/intelligence/seo';
import {saveSeoResearch} from '../../../../lib/intelligence/seo-store';

const valid=(value:unknown,max=200)=>typeof value==='string'&&value.trim().length>0&&value.trim().length<=max;
function statusFor(code:string){if(code==='missing_credentials'||code==='invalid_configuration')return 503;if(code==='invalid_auth')return 401;if(code==='permission_denied')return 403;if(code==='rate_limited')return 429;if(code==='timeout')return 504;return 502;}
export async function POST(request:Request){try{const body=await request.json() as Record<string,unknown>;const query=valid(body.query)?String(body.query).trim():valid(body.productService)?String(body.productService).trim():'';if(!query)return NextResponse.json({ok:false,error:'query or productService is required.'},{status:400});const productService=valid(body.productService)?String(body.productService).trim():query;const region=valid(body.region,120)?String(body.region).trim():'Unspecified';const language=valid(body.language,80)?String(body.language).trim():'English';const intent=valid(body.intent,40)?String(body.intent) as never:undefined;const includeSerpApi=body.includeSerpApi!==false;let google=null;let googleError:GoogleAdsProviderError|null=null;try{const adapter=createGoogleAdsAdapter();if(adapter.available)google=await adapter.research({query,location:region,language,seedKeywords:Array.isArray(body.seedKeywords)?body.seedKeywords.filter(item=>valid(item,120)).map(item=>String(item)):undefined});else googleError=new GoogleAdsProviderError('missing_credentials','Google Ads credentials are not configured.');}catch(error){googleError=error instanceof GoogleAdsProviderError?error:new GoogleAdsProviderError('unavailable','Google Ads research failed.');}let serp=null;let serpError:SerpApiError|null=null;if(includeSerpApi){try{const adapter=createSerpApiAdapter();if(adapter.available)serp=await adapter.research({query,region,engine:'google'});else serpError=new SerpApiError('missing_key','SerpApi is not configured.');}catch(error){serpError=error instanceof SerpApiError?error:new SerpApiError('unavailable','SerpApi research failed.');}}const result=saveSeoResearch(combineSeoIntelligence({query,productService,region,language,intent},google,serp));const connected=Boolean(google||serp);const status=googleError&&serpError&&!connected?'NOT CONNECTED':googleError||serpError?'PARTIAL':'CONNECTED';if(!connected)return NextResponse.json({ok:false,status,code:googleError?.code||serpError?.code||'unavailable',error:'No SEO research provider is connected.',result},{status:statusFor(googleError?.code||serpError?.code||'unavailable')});return NextResponse.json({ok:true,status,result,providerErrors:{google:googleError?.message||null,serpApi:serpError?.message||null}});}catch{return NextResponse.json({ok:false,error:'Invalid SEO research payload.'},{status:400});}}
